### ISSUE TITLE
Broken class on donation page

### ISSUE THREAD

**Issue by taskinoz** [GamesDoneQuick/donation-tracker#172]
When looking at the html I found one of the classes were broken on the donation page
![image](https://user-images.githubusercontent.com/7439692/72401095-38c53f00-379f-11ea-90b4-c07eec9cd4ef.png)

It seems that its an issue with the variable `commentstate` on the `templates/tracker/donation.html` page

**Comment by faultyserver** [comment]
hah! Nice find.

FWIW, that implementation of the donation page is no longer used (at least by GDQ), and has been replaced by a React-based version that lives at the URL [`/tracker/ui/donate/<eventid or shortname>`](https://gamesdonequick.com/tracker/ui/donate/agdq2020) for quite a while now. The code for that lives under [`bundles/tracker/donation`](https://github.com/GamesDoneQuick/donation-tracker/tree/master/bundles/tracker/donation).

My understanding is that the old form is ready and meant to be removed entirely, but that it just hasn't been done yet. With that, I'm not sure if this will get fixed in this repo (old forks may still be using this form, but they'd be pretty old and it's not worth maintaining in this repo for them).

Still an interesting case though!

**Comment by taskinoz** [comment]
Ahhh, so is it donate page that is causing the error on the donation viewing page?

**Comment by faultyserver** [comment]
Oh! I completely misread! I thought this was on the form, not viewing existing donations.

No, that is all still handled by django's templates, so this is totally valid. Sorry for jumping to the wrong conclusion.

**Comment by taskinoz** [comment]
No problem. That makes sense why I couldn't understand your reply.

I think the `commentstate` variable may be undefined in the template because it needs to reference an object, but I'm not sure how the data is laid out.

**Comment by faultyserver** [comment]
This looks like it was addressed in #191, so I'm going to close it as resolved. Loading the page, the commentstate is appropriately put as a class name on the `td`, and there's no "invalid variable" anymore.
